# Generated by Django 6.0.2 on 2026-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='maps_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Maps Linki'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
