# Generated by Django 6.0.2 on 2026-02-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0002_toilet_is_approved_toilet_maps_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toilet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tuvalet', 'verbose_name_plural': 'Tuvaletler'},
        ),
        migrations.AlterField(
            model_name='toilet',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Giriş Kodu (Varsa)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama/Notlar'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Ücretsiz mi?'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Enlem (Latitude)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Boylam (Longitude)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mekan Adı'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ücret (Varsa)'),
        ),
    ]
