# Generated by Django 6.0.2 on 2026-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0003_alter_toilet_options_alter_toilet_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Enlem (Latitude)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Boylam (Longitude)'),
        ),
    ]
