# Generated by Django 6.0.2 on 2026-02-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0004_alter_toilet_latitude_alter_toilet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Enlem (Latitude)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Boylam (Longitude)'),
        ),
    ]
