# Generated by Django 6.0.2 on 2026-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0005_alter_toilet_latitude_alter_toilet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Enlem (Latitude)'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Boylam (Longitude)'),
        ),
    ]
