# Generated by Django 6.0.2 on 2026-02-21 21:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0006_alter_toilet_latitude_alter_toilet_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalToilet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mekan Adı')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Enlem (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Boylam (Longitude)')),
                ('maps_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Maps Linki')),
                ('is_free', models.BooleanField(default=True, verbose_name='Ücretsiz mi?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ücret (Varsa)')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giriş Kodu (Varsa)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama/Notlar')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Eklenme Tarihi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tuvalet',
                'verbose_name_plural': 'historical Tuvaletler',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
