# Generated by Django 6.0.2 on 2026-02-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0007_historicaltoilet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('kapali', 'Tuvalet Kapalı / Bulunamadı'), ('ucretli', 'Ücretsiz Değil (Ücretli)'), ('sifre_yanlis', 'Giriş Kodu / Şifre Yanlış'), ('pis', 'Çok Kirli / Bakımsız'), ('konum_yanlis', 'Haritadaki Konum Yanlış'), ('diger', 'Diğer')], max_length=50, verbose_name='Şikayet Nedeni')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ek Açıklama (İsteğe Bağlı)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü mü?')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='toilets.toilet', verbose_name='İlgili Tuvalet')),
            ],
            options={
                'verbose_name': 'Tuvalet Şikayeti',
                'verbose_name_plural': 'Tuvalet Şikayetleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
